name: mapalus_flutter_commons
description: Common used stuff in flutter for mapalus project
version: 0.0.2
homepage: "https//www.mapalusindonesia.com"
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jiffy: ^5.0.0
  intl: ^0.17.0
  flutter_screenutil: ^5.6.0
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.2.1
  url_launcher: ^6.1.6
  transparent_image: ^2.0.0
  package_info_plus: ^3.0.2
  flutter_keyboard_visibility: ^5.4.0
  geolocator: ^9.0.2
  cached_network_image: ^3.2.2
  readmore: ^2.2.0
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  firebase_app_check: ^0.1.1+2
  firebase_crashlytics: ^3.0.3
  flutter_local_notifications: ^12.0.3+1
  infinite_scroll_pagination: ^3.2.0

  flutter_ringtone_player: ^3.2.0
  flutter_dropdown: ^1.0.1+hotfix.1
  device_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
