name: mapalus_flutter_commons
description: Common used flutter stuff in mapalus project
version: 0.0.8
homepage: "https//www.mapalusindonesia.com"
publish_to: 'none'

environment:
  sdk: '>=3.2.6 <4.0.0'
#  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jiffy: ^6.2.2
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.5.3
  url_launcher: ^6.2.4
  transparent_image: ^2.0.1
  package_info_plus: ^5.0.1
  flutter_keyboard_visibility: ^6.0.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.1
  readmore: ^2.2.0
  cloud_firestore: ^4.15.4
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.15
  firebase_app_check: ^0.2.1+13
  firebase_crashlytics: ^3.4.14
  flutter_local_notifications: ^16.3.2
  infinite_scroll_pagination: ^4.0.0

  flutter_ringtone_player: ^4.0.0+2
  flutter_dropdown: ^1.0.1+hotfix.1
  device_info_plus: ^9.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0


# derry config
scripts: derry.yaml
