name: mapalus_flutter_commons
description: Common used stuff in flutter for mapalus project
version: 0.0.2
homepage: "https//www.mapalusindonesia.com"
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  jiffy: ^5.0.0
  intl: ^0.17.0
  flutter_screenutil: ^5.6.0
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  flutter_rating_bar: ^4.0.1
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.2.1
  url_launcher: ^6.1.6
  transparent_image: ^2.0.0
  package_info_plus: ^3.0.1
  flutter_keyboard_visibility: ^5.4.0
  geolocator: ^9.0.2
  cached_network_image: ^3.2.2
  readmore: ^2.2.0
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  firebase_app_check: ^0.1.1+2
  firebase_crashlytics: ^3.0.3
  flutter_local_notifications: ^12.0.3
  infinite_scroll_pagination: ^3.2.0

  flutter_ringtone_player: ^3.2.0
  flutter_dropdown: ^1.0.1+hotfix.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
